services:
  postgres:
    image: postgres:16-alpine
    container_name: klyron_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: klyron_borhan
      POSTGRES_PASSWORD: "pOA521453269!@@"
      POSTGRES_DB: klyron_erp
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U klyron_borhan -d klyron_erp"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: klyron_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@klyron.com
      PGADMIN_DEFAULT_PASSWORD: "pOA521453269!@@"
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: klyron_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
