"""add team_id and criteria to assignment rules

Revision ID: b4b8c26e8cb0
Revises: 26eb0db0a6e5
Create Date: 2026-06-29 14:35:14.192937+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b4b8c26e8cb0'
down_revision: Union[str, None] = '26eb0db0a6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_assignment_rules', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('lead_assignment_rules', sa.Column('criteria', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'lead_assignment_rules', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_assignment_rules', type_='foreignkey')
    op.drop_column('lead_assignment_rules', 'criteria')
    op.drop_column('lead_assignment_rules', 'team_id')
    # ### end Alembic commands ###
