"""add_lead_management_tables

Revision ID: 26eb0db0a6e5
Revises: b5339fba6c82
Create Date: 2026-06-29 13:32:46.974609+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '26eb0db0a6e5'
down_revision: Union[str, None] = 'b5339fba6c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_activities_id'), 'lead_activities', ['id'], unique=False)
    op.create_table('lead_assignment_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_assignment_rules_id'), 'lead_assignment_rules', ['id'], unique=False)
    op.create_table('lead_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_tasks_id'), 'lead_tasks', ['id'], unique=False)
    op.create_table('lead_assignment_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['lead_assignment_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_assignment_distributions_id'), 'lead_assignment_distributions', ['id'], unique=False)
    op.create_table('lead_assignment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['lead_assignment_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_assignment_logs_id'), 'lead_assignment_logs', ['id'], unique=False)
    op.add_column('leads', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('leads', sa.Column('lead_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('leads', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('leads', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('converted_to_deal_id', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'leads', 'deals', ['converted_to_deal_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'created_by')
    op.drop_column('leads', 'converted_to_deal_id')
    op.drop_column('leads', 'last_activity_at')
    op.drop_column('leads', 'tags')
    op.drop_column('leads', 'lead_value')
    op.drop_column('leads', 'website')
    op.drop_column('leads', 'industry')
    op.drop_column('leads', 'company_name')
    op.drop_column('leads', 'title')
    op.drop_index(op.f('ix_lead_assignment_logs_id'), table_name='lead_assignment_logs')
    op.drop_table('lead_assignment_logs')
    op.drop_index(op.f('ix_lead_assignment_distributions_id'), table_name='lead_assignment_distributions')
    op.drop_table('lead_assignment_distributions')
    op.drop_index(op.f('ix_lead_tasks_id'), table_name='lead_tasks')
    op.drop_table('lead_tasks')
    op.drop_index(op.f('ix_lead_assignment_rules_id'), table_name='lead_assignment_rules')
    op.drop_table('lead_assignment_rules')
    op.drop_index(op.f('ix_lead_activities_id'), table_name='lead_activities')
    op.drop_table('lead_activities')
    # ### end Alembic commands ###
