"""Add gender_restriction to leave_types

Revision ID: b5339fba6c82
Revises: 7002d657b010
Create Date: 2026-06-28 11:41:42.863102+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b5339fba6c82'
down_revision: Union[str, None] = '7002d657b010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitments_id'), table_name='recruitments')
    op.drop_table('recruitments')
    op.create_foreign_key(None, 'attendance', 'work_locations', ['location_id'], ['id'])
    op.drop_column('employee_assets', 'condition')
    op.create_foreign_key(None, 'employee_documents', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(None, 'employees', 'employees', ['reporting_to'], ['id'])
    op.create_foreign_key(None, 'employees', 'designations', ['designation_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'shifts', ['shift_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'work_locations', ['work_location_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'employment_types', ['employment_type_id'], ['id'])
    op.create_foreign_key(None, 'leave_balances', 'leave_types', ['leave_type_id'], ['id'])
    op.add_column('leave_types', sa.Column('gender_restriction', sa.String(length=20), nullable=True))
    op.alter_column('leaves', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'leaves', 'leave_types', ['leave_type_id'], ['id'])
    op.create_foreign_key(None, 'payroll_items', 'salary_components', ['component_id'], ['id'])
    op.create_index(op.f('ix_requests_for_quotation_id'), 'requests_for_quotation', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_for_quotation_id'), table_name='requests_for_quotation')
    op.drop_constraint(None, 'payroll_items', type_='foreignkey')
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.alter_column('leaves', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('leave_types', 'gender_restriction')
    op.drop_constraint(None, 'leave_balances', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employee_documents', type_='foreignkey')
    op.add_column('employee_assets', sa.Column('condition', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_table('recruitments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('candidate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('applied_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('hired_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('recruitments_company_id_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('recruitments_department_id_fkey')),
    sa.ForeignKeyConstraint(['hired_by'], ['users.id'], name=op.f('recruitments_hired_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recruitments_pkey'))
    )
    op.create_index(op.f('ix_recruitments_id'), 'recruitments', ['id'], unique=False)
    # ### end Alembic commands ###
